{% set name = "libvdwxc" %}
{% set version = "0.4.0" %}
{% set sha256 = "5fcd37253489931b94ce865bb4e6942250665e269057a50bd532c8697ac19dc7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/libvdwxc/libvdwxc/-/archive/{{ version }}/libvdwxc-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libvdwxc', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [linux]
    - fftw * mpi_openmpi_*
    - openmpi
    - cmake >=3.1
    - ninja                      # [win]
    - perl

  run:
    - fftw * mpi_openmpi_*
    - openmpi

test:
  commands:
    - ls -l ${PREFIX}/lib                                     # [unix]
    - ls -l ${PREFIX}/bin                                     # [unix]
    # Verify if dynamic static 
    - test -f ${PREFIX}/lib/libvdwxc${SHLIB_EXT}              # [unix]
    # Verify include
    - test -f ${PREFIX}/include/vdwxc.h                       # [unix]
    - test -f ${PREFIX}/include/vdwxc_mpi.h                   # [unix]
    - test -f ${PREFIX}/include/vdwxcfort.f90                 # [unix]
    # # Inspect linkage
    # - xc-info 100                                           # [unix]
    # - ldd -v ${PREFIX}/lib/libvdwxc${SHLIB_EXT}               # [unix]
    # - otool -L $PREFIX/lib/libxc$SHLIB_EXT                  # [osx]
    # - conda inspect objects -p $PREFIX $PKG_NAME            # [osx]
    # - conda inspect linkages --show-files --groupby=dependency libxc  # [unix]

about:
  home: https://gitlab.com/libvdwxc/libvdwxc
  dev_url: https://gitlab.com/libvdwxc/libvdwxc
  doc_url: 
  license: GPL-3.-
  license_url: https://www.gnu.org/licenses/gpl-3.0.html
  license_file: COPYING
  license_family: GPL
  summary: Portable C library of density functionals with van der Waals interactions for density functional theory

extra:
  recipe-maintainers:
    - alchem0x2a
