name: Conda build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - name: setup environment
        uses: actions/checkout@v2
        
      - name: setup miniconda and activate base
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          
      - name: Prepare conda
        shell: bash -l {0}
        run: |
          conda info
          conda config --add channels conda-forge
          conda install conda-build
          
      - name: Try build conda image
        shell: bash -l {0}
        run: |
          conda build recipe
    
          
          
        
  
